# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ICO-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICO
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit'

  pod 'KakaoSDK'
  pod 'naveridlogin-sdk-ios'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
end
