name: App Store

on:
  push:
    tags:
      - "v*"

jobs:
  appstore:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
        ruby: [ '2.5', '2.6' ]

    steps:
      - run: fastlane release
